name: Qodana (with Caching)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/cache@v3  # Cache Qodana tool (if applicable)
        with:
          path: /path/to/qodana  # Replace with your cache path
          key: ${{ runner.os }}-qodana-${{ hashFiles('**/qodana-*.tar.gz') }}
          restore-keys: |
            ${{ runner.os }}-qodana-
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.2
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
